swagger: "2.0"
info:
  description: "此接口用於創建官方號內容"
  version: "v1"
  title: "創建官方號內容"
paths:
  /v1/whaleapi/social/media-topics:
    post:
      parameters:
        - name: "title"
          type: "string"
          description: "內容標題，創建長文內容時需要"
        - name: "body"
          type: "string"
          description: "内容"
          required: true
        - name: "images"
          type: string[]
          description: "圖片鏈接，創建短文內容附件圖片"
      responses:
        "200":
          description: "創建成功"
          schema:
            $ref: "#/definitions/create_media_topic_response"
        "400":
          description: "建立失敗，請求參數錯誤"
      request_body:
        type: "python"
        value: |
          curl -v -XPOST https://openapi.longportapp.com/v1/whaleapi/social/media-topics \
          -d '{ "body": "美股今天为什么涨了", "title": "" \
          -H "X-Api-Signature: {签名}" -H "X-Api-Key: {AppKey}" \
          -H "Authorization: {AccessToken}" -H "X-Timestamp: 1539095200.123"
          -H "Content-Type: application/json; charset=utf-8"
      response_body: { "code": 0, "message": "", "data": { "id": "1" } }
definitions:
  create_media_topic_response:
    type: "object"
    required:
      - id
    properties:
      id:
        type: "integer"
        description: "內容 ID"
        required: true
